config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for(:users)
  namespace :portfolio do 
    resources :art_items 
  end
  root to: "pages#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_item.rb
# frozen_string_literal: true

class ArtItem < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
    devise :database_authenticatable, :registerable

    has_many :art_items

    
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/art_items_controller.rb
class ArtItemsController < ApplicationController
  def index
    @art_item = ArtItem.all
  end

  def show
    @art_item = ArtItem.find params[:id]
  end

  def destroy
    @art_item = ArtItem.find(params[:id])
    @art_item.destroy
    flash[:success] = "Record #{@art_item.name} succesfully removed"
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/portfolio/art_items_controller.rb
class Portfolio::ArtItemsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user_art_items = current_user.art_items
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/art_items_helper.rb
module ArtItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio/art_items_helper.rb
module Portfolio::ArtItemsHelper
end

app/views/art_items/edit.html.slim
h2 Edit Art Item

== simple_form_for @art_item do |f|
	== f.input :name
	== f.input :price
	== f.submit
	

app/views/art_items/index.html.erb
- if @art_item.blank? 
    p The Art items in your portfolio will appear here! ;)
- else 
    p These are the art items currently in your portfolio

ul id = "art_item"
   - @art_item.each do |c|
        li
            - link_to c.name, {:action => 'show', :id => c.id}

app/views/art_items/index.html.slim
- if @art_item.any?
p These are the art items currently in your portfolio.
ul
   - @art_item.each do |c|
      li == link_to(c.name, c)
- else
p There are not any art item currently in your portfolio.

app/views/art_items/show.html.slim
h1 @art_item.name
p <strong>Price :</strong> @art_item.price
br
hr
== link_to("Delete", @art_item, method: :delete)
== link_to("Back", art_items_path)

app/views/layouts/application.html.slim
doctype html
html
  head
    title Pixeler
    == csrf_meta_tags
    == csp_meta_tag

    == stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .pageloader
    .infraloader
    == render 'shared/mobile_navbar'
    == render 'shared/main_sidebar'
    == render 'shared/quickview_trigger'
    == render 'shared/category_quickview'
    == render 'shared/shop_quickview'
    .shop-wrapper.has-background-image
      == yield

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/index.html.slim
h1 Pages#index
- if user_signed_in?
    ==link_to "Sign out", destroy_user_session_path, data:{method: :delete}
- else
    ==link_to "Sign in", new_user_session_path

app/views/portfolio/art_items/index.html.slim
table
    tbody
        - @user_art_items.each do | art_item |
            tr
                td=art_item.image
                td=art_item.name
                td=number_to_currency(art_item.price)
                td=time_ago_in_words(art_item.created_at)
                td=time_ago_in_words(art_item.updated_at)
    

app/views/shared/_main_sidebar.html.slim
.main-sidebar
  .sidebar-brand
    a[href="home.html"]
      == image_tag "logo/nephos.svg"
  .sidebar-inner
    ul.icon-menu
      li
        a#open-shop[href="javascript:void(0);"]
          svg.feather.feather-home[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"]
            polyline[points="9 22 9 12 15 12 15 22"]
      li
        a#open-cart[href="javascript:void(0);"]
          svg.feather.feather-shopping-cart[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            circle[cx="9" cy="21" r="1"]
            circle[cx="20" cy="21" r="1"]
            path[d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"]
          span#cart-dot.cart-items.gelatine.is-hidden
      li
        a#open-search[href="javascript:void(0);"]
          svg.feather.feather-search[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            circle[cx="11" cy="11" r="8"]
            line[x1="21" y1="21" x2="16.65" y2="16.65"]
        a#close-search.is-hidden.is-inactive[href="javascript:void(0);"]
          svg.feather.feather-x[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            line[x1="18" y1="6" x2="6" y2="18"]
            line[x1="6" y1="6" x2="18" y2="18"]
      li.is-hidden
        a#open-filters
          svg.feather.feather-filter[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            polygon[points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"]
      li#sidebar-wishlist-button.is-hidden
        a.sidebar-whishlist.modal-trigger[data-modal="add-to-wishlist-modal"]
          svg.feather.feather-heart[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"]
    ul.bottom-menu
      li.is-hidden-mobile
        .small-auth-loader
          .loader.is-loading
        a#login-link[href="authentication.html"]
          svg.feather.feather-user[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"]
            circle[cx="12" cy="7" r="4"]
        a#logout-link.is-hidden
          svg.feather.feather-log-out[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"]
            polyline[points="16 17 21 12 16 7"]
            line[x1="21" y1="12" x2="9" y2="12"]
      li#fold-link.fold-link
        a
          svg.feather.feather-arrow-left[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            line[x1="19" y1="12" x2="5" y2="12"]
            polyline[points="12 19 5 12 12 5"]

app/views/shared/_mobile_navbar.html.slim
nav.navbar.mobile-navbar.is-hidden-desktop.is-hidden-tablet[aria-label="main navigation"]
  .navbar-brand
    a.navbar-item[href="home.html"]
      == image_tag "logo/nephos.svg"
    a#sidebar-mode.navbar-item.is-icon.is-sidebar-toggler[href="javascript:void(0);"]
      svg.feather.feather-sidebar[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
        rect[x="3" y="3" width="18" height="18" rx="2" ry="2"]
        line[x1="9" y1="3" x2="9" y2="21"]
    .navbar-burger
      span
      span
      span
  .navbar-menu
    .navbar-item.has-dropdown
      a.navbar-link[href="account.html"]
        img#mobile-avatar[src="#{image_tag('avatars/altvatar.png')}" data-demo-src="#{image_tag('avatars/altvatar.png')}" alt=""]
        span#mobile-username.is-heading
          | Welcome, Guest
      .navbar-dropdown
        a.navbar-item[href="/"]
          | Home
        a.navbar-item.is-flex[href="cart-empty.html"]
          span
            | Cart
          span#mobile-cart-count.menu-badge
            | 0
        a.navbar-item[href="/account.html"]
          | Account
        a.navbar-item[href="/wishlists.html"]
          | Wishlists
        a.navbar-item[href="/orders.html"]
          | Orders
        a#mobile-login-link.navbar-item[href="authentication.html"]
          | Login
        a#mobile-register-link.navbar-item[href="authentication.html"]
          | Register
        a#mobile-logout-link.navbar-item.is-hidden
          | Logout
    .navbar-item.has-dropdown
      a.navbar-link
        svg.feather.feather-grid[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
          rect[x="3" y="3" width="7" height="7"]
          rect[x="14" y="3" width="7" height="7"]
          rect[x="14" y="14" width="7" height="7"]
          rect[x="3" y="14" width="7" height="7"]
        span.is-heading
          | Categories
      .navbar-dropdown
        a.navbar-item[href="products.html"]
          | House
        a.navbar-item[href="products.html"]
          | Office
        a.navbar-item[href="products.html"]
          | Kids
        a.navbar-item[href="products.html"]
          | Kitchen
        a.navbar-item[href="products.html"]
          | Accessories

app/views/shared/_quickview_trigger.html.slim
#quickview-trigger.menu-fab.is-hidden-mobile
  a.hamburger-btn[href="javascript:void(0);"]
    span.menu-toggle
      span.icon-box-toggle
        span.rotate
          i.icon-line-top
          i.icon-line-center
          i.icon-line-bottom

app/views/shared/_shop_quickview.html.slim
.shop-quickview.has-background-image[data-background="http://via.placeholder.com/1280x853" data-demo-background="assets/img/bg/sidebar.jpeg" style="background-image: url(&quot;http://via.placeholder.com/1280x853&quot;);"]
  .inner
    .quickview-header
      h2
        | Nephos
      span#close-shop-sidebar
        svg.feather.feather-x[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
          line[x1="18" y1="6" x2="6" y2="18"]
          line[x1="6" y1="6" x2="18" y2="18"]
    ul.shop-menu
      li
        a[href="shop.html"]
          span
            | Shop
          svg.feather.feather-grid[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            rect[x="3" y="3" width="7" height="7"]
            rect[x="14" y="3" width="7" height="7"]
            rect[x="14" y="14" width="7" height="7"]
            rect[x="3" y="14" width="7" height="7"]
      li
        a[href="products.html"]
          span
            | All Products
          svg.feather.feather-box[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"]
            polyline[points="3.27 6.96 12 12.01 20.73 6.96"]
            line[x1="12" y1="22.08" x2="12" y2="12"]
      li
        a[href="account.html"]
          span
            | My Account
          svg.feather.feather-user[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"]
            circle[cx="12" cy="7" r="4"]
      li
        a[href="orders.html"]
          span
            | My Orders
          svg.feather.feather-credit-card[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            rect[x="1" y="4" width="22" height="16" rx="2" ry="2"]
            line[x1="1" y1="10" x2="23" y2="10"]
      li
        a[href="wishlist.html"]
          span
            | My Wishlists
          svg.feather.feather-heart[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"]
    ul.user-profile
      li
        a[href="javascript:void(0);"]
          img#quickview-avatar[src="#{image_tag('avatars/altvatar.png')}" data-demo-src="#{image_tag('avatars/altvatar.png')}" alt=""]
          span.user
            span#quickview-username
              | Guest
            span#quickview-cart-count
              var
                | 0
              small
                | Items in Cart